Repository T-Systems-MMS/phonebook, pull requests merged in 2019-06, with the labels that each got.

#13 Set up CI with Azure Pipelines
  .gitignore
  Phonebook.Frontend/.dockerignore
  Phonebook.Frontend/.gitignore
  Phonebook.Frontend/.releaserc.json
  Phonebook.Frontend/Dockerfile
  Phonebook.Frontend/README.md
  Phonebook.Frontend/dev.Dockerfile
  Phonebook.Frontend/package-lock.json
  Phonebook.Frontend/package.json
  Phonebook.Frontend/src/app/shared/config/ColumnDefinitions.spec.ts
  Phonebook.Frontend/src/app/shared/states/Search.state.ts
  Phonebook.Frontend/version.js
  Readme.md
  azure-pipelines.yml
Labels: enhancement

#17 chore(mock): add more sample data
  Phonebook.Assets/Dockerfile
  Phonebook.Assets/assets/images/sample_1280.jpg
  Phonebook.Assets/assets/images/sample_1920.jpg
  Phonebook.Assets/assets/images/sample_640.jpg
  Phonebook.Assets/assets/roomplans/sample.svg
  Phonebook.Assets/nginx/conf.d/gzip.conf
  Phonebook.Assets/nginx/mime.types
  Phonebook.Assets/nginx/nginx.conf
  Phonebook.Frontend/mock/mock-db.json
Labels: enhancement

#24 Update .releaserc.json
  Phonebook.Frontend/.releaserc.json
Labels: bug

#33 Update Phonebook.Source.MockPeopleBackend.pr.yml for Azure Pipelines
  .azure/pipelines/pr/Phonebook.Source.MockPeopleBackend.pr.yml
  .azure/pipelines/production/Phonebook.Source.MockPeopleBackend.yml
Labels: bug, enhancement

#42 Add semantic-release/github to the release pipe
  Phonebook.Frontend/.releaserc.json
Labels: enhancement

#41 fix(table): fix filter and search with blanks
  Phonebook.Frontend/src/app/modules/table/table-logic.ts
Labels: bug

#40 Update Phonebook.Source.MockPeopleBackend.yml for Azure Pipelines
  .azure/pipelines/pr/Phonebook.Source.MockPeopleBackend.pr.yml
  .azure/pipelines/production/Phonebook.Source.MockPeopleBackend.yml
Labels: bug

#46 fix(user): update the issue-link in feedback-drawer-sheet
  Phonebook.Frontend/src/app/shared/directives/feedback-drawer/feedback-drawer-sheet/feedback-drawer-sheet.component.html
Labels: enhancement

#50 Update .releaserc.json
  Phonebook.Frontend/.releaserc.json
Labels: bug

#56 feat(app): show generated release notes
  Phonebook.Frontend/.releaserc.json
  Phonebook.Frontend/package-lock.json
  Phonebook.Frontend/package.json
  Phonebook.Frontend/proxy.conf.json
  Phonebook.Frontend/src/app/app.component.spec.ts
  Phonebook.Frontend/src/app/services/release-info.service.spec.ts
  Phonebook.Frontend/src/app/services/release-info.service.ts
  Phonebook.Frontend/src/app/shared/dialogs/release-notification-dialog/release-notification.dialog.html
  Phonebook.Frontend/src/app/shared/dialogs/release-notification-dialog/release-notification.dialog.ts
Labels: enhancement
