Repository T-Systems-MMS/phonebook, pull requests merged in 2019-09, with the labels that each got.

#202 feat(information-page): rework information page
  .all-contributorsrc
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.html
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.scss
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.spec.ts
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.ts
  Phonebook.Frontend/src/app/pages/page-information/page-information.module.ts
  Phonebook.Frontend/src/assets/CONTRIBUTORS.md
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
  Phonebook.Frontend/src/styles.scss
Labels: feature

#203 fix(notification-dialog): rename pb-card-container
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.html
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.scss
Labels: BLOCKED, bug

#206 feat(filter): make filter for employee-type possible
  Phonebook.Frontend/src/app/modules/table/components/table/table.component.html
  Phonebook.Frontend/src/app/modules/table/table-logic.spec.ts
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.ts
  Phonebook.Frontend/src/app/shared/config/ColumnDefinitions.spec.ts
  Phonebook.Frontend/src/app/shared/config/columnDefinitions.ts
  Phonebook.Frontend/src/app/shared/config/columnTranslate.ts
  Phonebook.Frontend/src/app/shared/mocks/person.ts
  Phonebook.Frontend/src/app/shared/models/classes/Person.ts
  Phonebook.Frontend/src/app/shared/models/classes/index.ts
  Phonebook.Frontend/src/app/shared/models/enumerables/ColumnId.ts
  Phonebook.Frontend/src/app/shared/models/enumerables/PersonStatus.ts
  Phonebook.Frontend/src/app/shared/models/enumerables/index.ts
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
Labels: feature

#181 fix(table-settings-popup): add close button and search-hint
  Phonebook.Frontend/src/app/app.module.ts
  Phonebook.Frontend/src/app/modules/table/dialogs/table-settings-dialog/table-settings.dialog.html
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
  Phonebook.Frontend/src/styles.scss
  Phonebook.Frontend/src/styles/overrides.scss
  docs/pages/development-guides/frontend/translation-guide.md
Labels: bug

#219 feat(welcome-page): list contributors on welcome page
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.html
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.scss
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.ts
  Phonebook.Frontend/src/app/pages/page-information/page-information.module.ts
  Phonebook.Frontend/src/app/shared/components/contributors/contributors.component.html
  Phonebook.Frontend/src/app/shared/components/contributors/contributors.component.scss
  Phonebook.Frontend/src/app/shared/components/contributors/contributors.component.spec.ts
  Phonebook.Frontend/src/app/shared/components/contributors/contributors.component.ts
  Phonebook.Frontend/src/app/shared/components/contributors/contributors.module.ts
  Phonebook.Frontend/src/app/shared/dialogs/dialogs.module.ts
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.html
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.scss
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
  Phonebook.Frontend/src/styles.scss
Labels: feature

#220 fix(bug-report-dialog): Don't show Bug Report Dialog if no ravenUrl is provided
  Phonebook.Demo/values.yml
  Phonebook.Frontend/src/app/app.component.ts
  Phonebook.Frontend/substitute_variables.sh
Labels: chore

#288 chore: update package.json
  Phonebook.Frontend/package.json
Labels: chore

#292 chore: remove todos in runtime and handle related errors
  Phonebook.Frontend/src/app/modules/profile-picture/components/change-profile-picture/change-profile-picture.component.ts
  Phonebook.Frontend/src/app/modules/profile-picture/components/profile-picture/profile-picture.component.html
  Phonebook.Frontend/src/app/modules/profile-picture/components/profile-picture/profile-picture.component.ts
  Phonebook.Frontend/src/app/modules/profile-picture/profile-picture.service.ts
  Phonebook.Frontend/src/app/services/api/current-user.service.ts
  Phonebook.Frontend/src/app/shared/directives/feedback-drawer/feedback-drawer-sheet/feedback-drawer-sheet.component.html
  Phonebook.Frontend/src/environments/EnvironmentInterfaces.ts
  Phonebook.Frontend/src/environments/runtime-environment.ts
Labels: chore

#333 chore(renovate): include autolabeling and automerge
  renovate.json
Labels: chore
