Repository T-Systems-MMS/phonebook, pull requests merged in 2019-12, with the labels that each got.

#385 chore(helm): update traefik chart
  Phonebook/phonebook/requirements.lock
  Phonebook/phonebook/requirements.yaml
Labels: automerge

#429 fix(app): make rocketChat Link work
  .azure/pipelines/pr/Phonebook.pr.yml
  Phonebook.Demo/values.yml
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.ts
  Phonebook.Frontend/src/environments/EnvironmentInterfaces.ts
  Phonebook.Frontend/src/environments/runtime-environment.ts
  Phonebook.Frontend/src/index.html
  Phonebook.Frontend/substitute_variables.sh
  Phonebook/phonebook/templates/frontend-deployment.yaml
  Phonebook/phonebook/values.yaml
  Phonebook/readme.md
Labels: automerge

#369 feat(information-page): user-guide-link on information page
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.html
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.scss
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
  Phonebook.Frontend/src/styles/overrides.scss
Labels: feature

#382 feat(incorrect-information-button): Information button about how incorrect data can be changed
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.scss
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.ts
  Phonebook.Frontend/src/app/shared/dialogs/dialogs.module.ts
  Phonebook.Frontend/src/app/shared/dialogs/user-information/incorrect-user-information.component.html
  Phonebook.Frontend/src/app/shared/dialogs/user-information/incorrect-user-information.component.scss
  Phonebook.Frontend/src/app/shared/dialogs/user-information/incorrect-user-information.component.spec.ts
  Phonebook.Frontend/src/app/shared/dialogs/user-information/incorrect-user-information.component.ts
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
Labels: feature

#444 fix(theme): make links more readable
  Phonebook.Frontend/src/app/modules/table/components/table/table.component.html
  Phonebook.Frontend/src/app/modules/table/table.module.ts
  Phonebook.Frontend/src/app/shared/components/add-filter/add-filter.component.html
  Phonebook.Frontend/src/app/shared/components/add-filter/add-filter.component.scss
  Phonebook.Frontend/src/app/shared/components/add-filter/add-filter.component.theme.scss
  Phonebook.Frontend/src/app/shared/components/add-filter/add-filter.module.ts
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html
  Phonebook.Frontend/src/app/shared/components/user/user.module.ts
  Phonebook.Frontend/src/styles.scss
  Phonebook.Frontend/src/styles/themes.scss
Labels: bug

#441 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: automerge, docs

#463 Update protractor.conf.js
  Phonebook.Frontend/protractor.conf.js
Labels: automerge

#460 fix(user-detail): too much whitespace
  Phonebook.Frontend/src/app/modules/rooms/components/building/building.component.html
  Phonebook.Frontend/src/app/modules/rooms/components/city/city.component.html
  Phonebook.Frontend/src/app/modules/rooms/components/floor/floor.component.html
  Phonebook.Frontend/src/app/modules/rooms/components/room/room.component.html
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html
Labels: bug

#208 fix(App.Modules.Table): validate phonenumber for stupid softphones #196
  Phonebook.Frontend/src/app/modules/rooms/components/building/building.component.html
  Phonebook.Frontend/src/app/modules/rooms/components/city/city.component.html
  Phonebook.Frontend/src/app/modules/rooms/components/room/room.component.html
  Phonebook.Frontend/src/app/modules/rooms/rooms.module.ts
  Phonebook.Frontend/src/app/modules/table/components/table/table.component.html
  Phonebook.Frontend/src/app/modules/table/table.module.ts
  Phonebook.Frontend/src/app/shared/components/user/user-small-card/user-small-card.component.html
  Phonebook.Frontend/src/app/shared/components/user/user-small-card/user-small-card.component.spec.ts
  Phonebook.Frontend/src/app/shared/components/user/user-tiny-card/user-tiny-card.component.html
  Phonebook.Frontend/src/app/shared/components/user/user.module.ts
  Phonebook.Frontend/src/app/shared/interactive-attribute-field/interactive-attribute-field.component.html
  Phonebook.Frontend/src/app/shared/interactive-attribute-field/interactive-attribute-field.module.ts
  Phonebook.Frontend/src/app/shared/pipes/pipes.module.ts
  Phonebook.Frontend/src/app/shared/pipes/telephone.pipe.spec.ts
  Phonebook.Frontend/src/app/shared/pipes/telephone.pipe.ts
Labels: bug
