Repository T-Systems-MMS/phonebook, pull requests merged in 2019-07, with the labels that each got.

#38 feat(app): add Color Theme Switcher
  Phonebook.Frontend/src/app/app.component.spec.ts
  Phonebook.Frontend/src/app/app.component.ts
  Phonebook.Frontend/src/app/pages/settings/settings.component.html
  Phonebook.Frontend/src/app/pages/settings/settings.component.ts
  Phonebook.Frontend/src/app/services/release-info.service.spec.ts
  Phonebook.Frontend/src/app/services/theme.service.ts
  Phonebook.Frontend/src/app/shared/dialogs/release-notification-dialog/release-notification.dialog.html
  Phonebook.Frontend/src/app/shared/models/enumerables/Theme.ts
  Phonebook.Frontend/src/app/shared/states/App.state.spec.ts
  Phonebook.Frontend/src/app/shared/states/App.state.ts
  Phonebook.Frontend/src/assets/defaultFeatureFlags.json
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
  Phonebook.Frontend/src/index.html
  Phonebook.Frontend/src/styles/themes.scss
  Phonebook.Frontend/src/styles/themes/blue.scss
  Phonebook.Frontend/src/styles/themes/magenta.scss
  docs/developer-guide/theme-development.md
  phonebook.code-workspace
Labels: enhancement

#60 Use GitHub-Pages for Documentation #54
  .gitignore
  Phonebook.Frontend/README.md
  Readme.md
  docs/.gitignore
  docs/Gemfile
  docs/Gemfile.lock
  docs/README.md
  docs/_config.yml
  docs/_includes/nav.html
  docs/_layouts/default.html
  docs/_sass/custom/custom.scss
  docs/assets/images/traefik-dashboard.png
  docs/assets/js/search-data.json
  docs/developer-guide/css-guide.md
  docs/developer-guide/general-guide.md
  docs/developer-guide/get-started.md
  docs/developer-guide/theme-development.md
  docs/infrastructure-guide/get-started.md
  docs/pages/404.html
  docs/pages/development-guides/backend/backend.md
  docs/pages/development-guides/development-guides.md
  docs/pages/development-guides/frontend/frontend.md
  docs/pages/development-guides/frontend/general-commands.md
  docs/pages/development-guides/frontend/general-guide.md
  docs/pages/development-guides/frontend/getting-started.md
  docs/pages/development-guides/frontend/release-guide.md
  docs/pages/development-guides/frontend/theme-development.md
  docs/pages/development-guides/frontend/translation-guide.md
  docs/pages/development-guides/general-guide.md
  docs/pages/development-guides/good-to-know/good-to-know.md
  docs/pages/development-guides/media/images/git-cz.png
  docs/pages/doc-guides/get-started.md
  docs/pages/infrastructure-guides/infrastructure-guides.md
  docs/pages/user-docs/user-docs.md
  docs/welcome.md
Labels: enhancement

#93 fix(floorplan): color polygons as well
  Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.ts
Labels: bug

#111 fix(floorplan): add loadSVG to ngOnChanges
  Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.ts
Labels: bug

#112 docs(docs): remove not necessary command
  docs/pages/development-guides/frontend/getting-started.md
Labels: docs

#115 docs(docs): update link
  Phonebook.Frontend/README.md
Labels: docs

#113 docs(docs): insert community information into readme.md
  docs/README.md
Labels: docs

#28 feature(kubernetes): add kubernetes deployment
  .azure/pipelines/pr/Phonebook.pr.yml
  .azure/pipelines/production/Phonebook.yml
  Phonebook.Demo/Phonebook.Assets.yml
  Phonebook.Demo/Phonebook.MockBackend.yml
  Phonebook.Demo/helm-rbac.yml
  Phonebook.Demo/phonebook-namespace.yml
  Phonebook.Demo/readme.md
  Phonebook.Demo/values.yml
  Phonebook.Frontend/docker-compose.yml
  Phonebook/.gitignore
  Phonebook/phonebook/.helmignore
  Phonebook/phonebook/Chart.yaml
  Phonebook/phonebook/requirements.lock
  Phonebook/phonebook/requirements.yaml
  Phonebook/phonebook/templates/NOTES.txt
  Phonebook/phonebook/templates/_helpers.tpl
  Phonebook/phonebook/templates/frontend-deployment.yaml
  Phonebook/phonebook/templates/frontend-ingress.yaml
  Phonebook/phonebook/templates/frontend-service.yaml
  Phonebook/phonebook/templates/tests/test-connection.yaml
  Phonebook/phonebook/values.yaml
  Phonebook/readme.md
  phonebook.code-workspace
Labels: enhancement
