Repository T-Systems-MMS/phonebook, pull requests merged in 2019-10, with the labels that each got.

#348 feat(incorrect-information-button): Information button about how to change your data
  Phonebook.Frontend/.vscode/settings.json
  Phonebook.Frontend/package-lock.json
  Phonebook.Frontend/src/app/app.module.ts
  Phonebook.Frontend/src/app/pages/dashboard/dashboard.component.html
  Phonebook.Frontend/src/app/pages/dashboard/dashboard.component.ts
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.html
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.ts
  Phonebook.Frontend/src/app/pages/page-information/page-information.module.ts
  Phonebook.Frontend/src/app/pages/settings/settings.component.html
  Phonebook.Frontend/src/app/pages/settings/settings.component.ts
  Phonebook.Frontend/src/app/pages/settings/settings.module.ts
  Phonebook.Frontend/src/app/pages/users/user-detail-page/user-detail-page.component.ts
  Phonebook.Frontend/src/app/pages/users/user-detail-page/user-detail-page.module.ts
  Phonebook.Frontend/src/app/pages/users/user-detail-page/user-detail-page.resolver.ts
  Phonebook.Frontend/src/app/pages/users/user-pages-routing.module.ts
  Phonebook.Frontend/src/app/pages/users/user-pages.module.ts
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.scss
  Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.ts
  Phonebook.Frontend/src/app/shared/dialogs/dialogs.module.ts
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.spec.ts
  Phonebook.Frontend/src/app/shared/dialogs/userinformation/dialog.component.html
  Phonebook.Frontend/src/app/shared/dialogs/userinformation/dialog.component.scss
  Phonebook.Frontend/src/app/shared/dialogs/userinformation/dialog.component.spec.ts
  Phonebook.Frontend/src/app/shared/dialogs/userinformation/dialog.component.ts
  package-lock.json
Labels: feature

#360 feat: add .gitattributes
  .gitattributes
Labels: feature

#363 chore: create .prettierrc.json
  Phonebook.Frontend/.prettierrc.json
  phonebook.code-workspace
Labels: feature

#370 chore: add automerge
  .github/workflows/main.yml
Labels: automerge

#388 bug(table-configurator): prevent multiple dialogs (#387)
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.ts
Labels: bug

#376 feat(navbar): profile Picture in Navbar instead of person-icon
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.scss
  Phonebook.Frontend/src/styles.scss
  Phonebook.Frontend/src/styles/mixins.scss
Labels: feature

#328 feat(skip-dialog): Enhance popup usability and design (#118)
  Phonebook.Frontend/src/app/app.component.ts
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.html
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.ts
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
Labels: feature

#400 fix(skip-start-dialogs): skip release information and bug report dialog
  Phonebook.Frontend/src/app/app.component.ts
Labels: bug
