Repository T-Systems-MMS/phonebook, pull requests merged in 2019-08, with the labels that each got.

#123 feature(app): open sidenav on small devices on the right side
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
Labels: enhancement

#130 chore(build): speed up frontend-pr build
  .azure/pipelines/pr/Phonebook.Frontend.pr.yml
Labels: chore

#144 docs: update contributors
  docs/README.md
Labels: docs

#138 fix(frontend-search): search does not reset on user page
  Phonebook.Frontend/src/app/shared/states/Search.state.ts
Labels: bug

#143 docs: update doc-guides/get-started.md
  docs/pages/doc-guides/get-started.md
Labels: docs

#141 fix(magenta-accent): change accent from black to lightblue
  Phonebook.Frontend/src/styles/themes/magenta.scss
Labels: bug

#124 chore(tooling): pr preview
  .azure/pipelines/Phonebook.preview.yml
  Phonebook.Demo/Phonebook.Assets.yml
  Phonebook.Demo/Phonebook.MockBackend.yml
  Phonebook.Demo/values.yml
  Phonebook/phonebook/templates/frontend-ingress.yaml
Labels: enhancement

#133 fix(frontend): opensearch.xml available under root
  Phonebook.Frontend/.dockerignore
  Phonebook.Frontend/Dockerfile
  Phonebook.Frontend/nginx/nginx.conf
  Phonebook.Frontend/opensearch.xml
  Phonebook.Frontend/src/index.html
  Phonebook/phonebook/templates/frontend-deployment.yaml
Labels: bug

#135 feat(frontend): make environment tag configurable
  Phonebook.Demo/values.yml
  Phonebook.Frontend/docker-compose.yml
  Phonebook.Frontend/globals.js
  Phonebook.Frontend/src/app/app.module.ts
  Phonebook.Frontend/src/app/modules/feature-flag/feature-flag.service.spec.ts
  Phonebook.Frontend/src/app/modules/feature-flag/feature-flag.service.ts
  Phonebook.Frontend/src/app/pages/page-information/page-information.component.ts
  Phonebook.Frontend/src/app/pages/page-information/page-information.module.ts
  Phonebook.Frontend/src/app/services/environment.service.ts
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.ts
  Phonebook.Frontend/src/app/shared/error/error.module.ts
  Phonebook.Frontend/src/environments/EnvironmentInterfaces.ts
  Phonebook.Frontend/src/environments/runtime-environment.ts
  Phonebook.Frontend/src/index.html
  Phonebook.Frontend/src/main.ts
  Phonebook.Frontend/substitute_variables.sh
  Phonebook/phonebook/templates/frontend-deployment.yaml
  Phonebook/readme.md
Labels: feature

#159 docs: update frontend-link in general-guide.md
  docs/pages/development-guides/general-guide.md
Labels: bug, docs

#131 feat(welcome-popup): redesign welcome popup
  Phonebook.Frontend/src/app/modules/profile-picture/components/profile-picture/profile-picture.component.scss
  Phonebook.Frontend/src/app/shared/components/search/search.component.scss
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.html
  Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.scss
  Phonebook.Frontend/src/app/shared/interactive-attribute-field/interactive-attribute-field.component.html
  Phonebook.Frontend/src/styles/mixins.scss
  Phonebook.Frontend/src/styles/themes.scss
Labels: feature

#163 feat(chore): add i18n code-snippets
  Phonebook.Frontend/.gitignore
  Phonebook.Frontend/.vscode/i18n.code-snippets
Labels: chore

#139 feat(release-notification): update-notification-badge
  .azure/pipelines/Phonebook.preview.yml
  Phonebook.Frontend/src/app/app.module.ts
  Phonebook.Frontend/src/app/services/release-info.service.ts
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
  Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.ts
  Phonebook.Frontend/src/i18n/messages.de.xlf
  Phonebook.Frontend/src/i18n/messages.en.xlf
  Phonebook.Frontend/src/i18n/messages.test.xlf
  Phonebook.Frontend/src/i18n/messages.xlf
Labels: feature

#166 fix(release-notification): Hide release-notification-badge if release-dialog was clicked
  Phonebook.Frontend/src/app/services/release-info.service.ts
Labels: bug

#185 Add main.yml
  .github/workflows/main.yml
Labels: automerge

#189 docs: init allcontributors-Bot
  .all-contributorsrc
  docs/CONTRIBUTORS.md
  docs/README.md
Labels: automerge

#192 docs: allcontributors description as issue template + description in docu
  .github/ISSUE_TEMPLATE/add-contributors.md
  docs/pages/development-guides/general-guide.md
Labels: docs

#197 Use new Credentials
  .azure/pipelines/Phonebook.preview.yml
  .azure/pipelines/production/Phonebook.Frontend.yml
Labels: automerge

#198 Update Phonebook.Assets.yml for Azure Pipelines
  .azure/pipelines/production/Phonebook.Assets.yml
  .azure/pipelines/production/Phonebook.Source.MockPeopleBackend.yml
Labels: automerge

#205 chore(issue-templates): remove enhancement-template
  .github/ISSUE_TEMPLATE/enhancement_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: automerge

#200 [docs] add links to the azure devops project in the general developer documentation
  docs/pages/development-guides/general-guide.md
Labels: docs
